[package]
name = "condition_variable"
version = "0.1.3"
description = "Condition Variables (CondVars) made easy"
homepage = "https://github.com/manuels/condition_variable.rs"
license = " GPL-2.0"
authors = ["Manuel Sch√∂lling <manuel.schoelling@gmx.de>"]
